version: '3.1'


# to start multiple docker files use this command

#  docker-compose -f docker-compose-abc.yml -f docker-compose-xyz  up

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres # - this is a default user and pw OOTB from PG.
      - POSTGRES_PASSWORD=postgres
      # -  POSTGRES_DATABASE=mypostgres - needs more set up to override the default postgres DB that is created by default by Postgres OOTB.
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    command: -p 5433     # PG runs on  5433 and NOT the default of 5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
