spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  profiles:
    active: application
    default: application
  sql:
    init:
      continue-on-error: true
#  flyway:
#    baseline-on-migrate: false
#    enabled: true
#    locations: classpath:db/migration
#    validate-on-migrate: false
  test:
    database:

services:
  app:
    container_name: back-end
    depends_on:
        -postgres

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
        - POSTGRES_USER=postgres # - this is a default user and pw OOTB from PG.
        - POSTGRES_PASSWORD=postgres
        # -  POSTGRES_DATABASE=mypostgres - needs more set up to override the default postgres DB that is created by default by Postgres OOTB.
    expose:
        - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
        - "5433:5433"
    command: -p 5433     # PG runs on  5433 and NOT the default of 5432
    volumes:
        - db:/var/lib/postgresql/data

org:
  hibernate:
    dialect:
      Dialect:org.hibernate.dialect.PostgreSQL8Dialect
    connection:
      url:org.hibernate.dialect.PostgreSQLDialect

#liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yml

#javax:
#  persistence:
#    jdbc:
#      url:jdbc:mysql://localhost:3306/db_example

logging:
  level:
    sql: debug
    org.springframework.orm.jpa: TRACE
    org.springframework.transaction: TRACE
    org.hibernate.org.hibernate.type.descriptor.sql: TRACE
